/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_coapie_piebox_NativeDaemons */

#ifndef _Included_com_coapie_piebox_NativeDaemons
#define _Included_com_coapie_piebox_NativeDaemons
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    setNativeRepoParam
 * Signature: (Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_setNativeRepoParam
  (JNIEnv *, jobject, jstring, jshort);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    getNativeRepoStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_getNativeRepoStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    startNativeRepo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_startNativeRepo
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    stopNativeRepo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_stopNativeRepo
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    restartNativeRepo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_restartNativeRepo
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    cleanNativeRepo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_cleanNativeRepo
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    setNativeTransParam
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_setNativeTransParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    getNativeTransStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_getNativeTransStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    startNativeTrans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_startNativeTrans
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    stopNativeTrans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_stopNativeTrans
  (JNIEnv *, jobject);

/*
 * Class:     com_coapie_piebox_NativeDaemons
 * Method:    restartNativeTrans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coapie_piebox_NativeDaemons_restartNativeTrans
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
