/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IARCH_MGMT_H
#define IARCH_MGMT_H

/* base includes */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>

#include "osapi.h"
#include "cmp.h"
#include "fixarray.h"

#include "./gen-cmp/iarch_mgmt_types.h"

#endif /* IARCH_MGMT_H */
